<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="CertifyMe.pk Blog - IT Certification insights and career advice">
    <title>Blog - CertifyMe.pk</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="./assets/css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">

    <style>
        .blogs-page-section {
            padding: 120px 20px 80px;
            background: var(--light-gray);
            min-height: 100vh;
        }

        .blogs-page-header {
            text-align: center;
            margin-bottom: 60px;
        }

        .blogs-page-title {
            font-size: 48px;
            font-weight: 700;
            color: var(--dark-charcoal);
            margin-bottom: 15px;
        }

        .blogs-page-subtitle {
            font-size: 20px;
            color: var(--text-gray);
        }

        .blogs-container {
            max-width: 1200px;
            margin: 0 auto;
        }

        .all-blogs-grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(350px, 1fr));
            gap: 30px;
            margin-top: 40px;
        }

        .blog-card {
            background: white;
            border-radius: 20px;
            overflow: hidden;
            transition: all 0.3s ease;
            cursor: pointer;
            box-shadow: 0 5px 20px rgba(0,0,0,0.08);
        }

        .blog-card:hover {
            transform: translateY(-10px);
            box-shadow: 0 15px 40px rgba(0,0,0,0.15);
        }

        .blog-image {
            width: 100%;
            height: 250px;
            object-fit: cover;
        }

        .blog-content {
            padding: 25px;
        }

        .blog-category {
            display: inline-block;
            padding: 6px 15px;
            background: linear-gradient(135deg, var(--primary-blue) 0%, var(--deep-purple) 100%);
            color: white;
            border-radius: 20px;
            font-size: 13px;
            font-weight: 600;
            margin-bottom: 15px;
        }

        .blog-title {
            font-size: 22px;
            font-weight: 700;
            color: var(--dark-charcoal);
            margin-bottom: 15px;
            line-height: 1.4;
            min-height: 60px;
        }

        .blog-excerpt {
            font-size: 15px;
            color: var(--text-gray);
            line-height: 1.6;
            margin-bottom: 20px;
            display: -webkit-box;
            -webkit-line-clamp: 3;
            -webkit-box-orient: vertical;
            overflow: hidden;
        }

        .blog-meta {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding-top: 15px;
            border-top: 1px solid var(--light-gray);
        }

        .blog-date {
            font-size: 14px;
            color: var(--text-gray);
        }

        .read-more {
            color: var(--primary-blue);
            font-weight: 600;
            font-size: 14px;
            text-decoration: none;
            display: flex;
            align-items: center;
            gap: 5px;
        }

        .read-more:hover {
            gap: 10px;
        }

        @media (max-width: 768px) {
            .blogs-page-title {
                font-size: 36px;
            }

            .all-blogs-grid {
                grid-template-columns: 1fr;
                gap: 20px;
            }
        }
    </style>
</head>

<body>

<?php include 'includes/page-parts/header.php'; ?>

<section class="blogs-page-section">
    <div class="blogs-container">
        <div class="blogs-page-header">
            <h1 class="blogs-page-title">Our Blog</h1>
            <p class="blogs-page-subtitle">Expert tips, industry insights, and career advice for IT professionals</p>
        </div>

        <div class="all-blogs-grid" id="allBlogsGrid">
            <!-- All blog posts will be generated by JavaScript -->
        </div>
    </div>
</section>

<?php include 'includes/page-parts/footer.php'; ?>

<script src="./assets/js/script.js"></script>
<script>
    // Render all blog posts
    const grid = document.getElementById('allBlogsGrid');
    
    grid.innerHTML = blogPosts.map((post, index) => `
        <div class="blog-card" onclick="window.location.href='blog-page.php?id=${index}'">
            <img src="${post.image}" alt="${post.title}" class="blog-image">
            <div class="blog-content">
                <span class="blog-category">${post.category}</span>
                <h3 class="blog-title">${post.title}</h3>
                <p class="blog-excerpt">${post.excerpt}</p>
                <div class="blog-meta">
                    <span class="blog-date">📅 ${post.date}</span>
                    <a href="blog-page.php?id=${index}" class="read-more">
                        Read More <i class="fas fa-arrow-right"></i>
                    </a>
                </div>
            </div>
        </div>
    `).join('');
</script>

</body>
</html>
