 <section class="blog-section" id="blog">
        <div class="container">
            <div class="section-header">
                <h2 class="section-title">Latest from Our Blog</h2>
                <p class="section-subtitle">Expert tips, industry insights, and career advice</p>
            </div>
            <div class="blog-grid" id="blogGrid">
                <!-- Blog posts will be generated by JavaScript -->
            </div>
        </div>
    </section>