<section class="faq-section" id="faq">
        <div class="container">
            <div class="section-header">
                <h2 class="section-title">Frequently Asked Questions</h2>
                <p class="section-subtitle">Everything you need to know about our certifications and training</p>
            </div>
            <div class="faq-accordion" id="faqAccordion">
                <!-- FAQ items will be generated by JavaScript -->
            </div>
        </div>
    </section>