<footer class="footer">
        <div class="container">
            <div class="footer-content">
                <div class="footer-col">
                    <h3>About CertifyMe.pk</h3>
                    <p>Pakistan's premier IT certification and training platform, empowering professionals with industry-recognized credentials and career advancement opportunities.</p>
                    <div class="trust-badges">
                        <span class="badge">Pearson VUE</span>
                        <span class="badge">Prometric</span>
                        <span class="badge">PSEB</span>
                    </div>
                </div>
                <div class="footer-col">
                    <h3>Quick Links</h3>
                    <ul>
                        <li><a href="#home">Home</a></li>
                        <li><a href="#certifications">Certifications</a></li>
                        <li><a href="#training">Training</a></li>
                        <li><a href="#testing-center">Testing Center</a></li>
                        <li><a href="#success-stories">Success Stories</a></li>
                        <li><a href="#blog">Blog</a></li>
                        <li><a href="#contact">Contact</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h3>Top Certifications</h3>
                    <ul>
                        <li><a href="#certifications">AWS Solutions Architect</a></li>
                        <li><a href="#certifications">Microsoft Azure Administrator</a></li>
                        <li><a href="#certifications">CompTIA Security+</a></li>
                        <li><a href="#certifications">Google Cloud Associate</a></li>
                        <li><a href="#certifications">Cisco CCNA</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h3>Contact</h3>
                    <ul>
                        <li>📍 Plaza 54, Abdali Road, Multan</li>
                        <li>📞 +92-61-4567890</li>
                        <li>📧 info@certifyme.pk</li>
                        <li>🕐 Mon-Sat: 9 AM - 8 PM</li>
                    </ul>
                </div>
            </div>
            <div class="footer-bottom">
                <p>&copy; 2025 CertifyMe.pk. All rights reserved. | A <a href="https://bixitech.com" target="_blank">BixiTech.com</a> Initiative</p>
            </div>
        </div>
    </footer>

    <!-- Certification Detail Modal -->
    <div class="modal" id="certificationModal">
        <div class="modal-content">
            <button class="modal-close" onclick="closeModal()">&times;</button>
            <div class="modal-body" id="modalBody">
                <!-- Modal content will be generated by JavaScript -->
            </div>
        </div>
    </div>

    <!-- Success Story Modal -->
    <div class="modal" id="successStoryModal">
        <div class="modal-content">
            <button class="modal-close" onclick="closeSuccessModal()">&times;</button>
            <div class="modal-body" id="successModalBody">
                <!-- Modal content will be generated by JavaScript -->
            </div>
        </div>
    </div>

   
</body>
</html>