<section class="certifications-section" id="certifications">
        <div class="container">
            <div class="section-header">
                <h2 class="section-title">Popular Certifications</h2>
                <p class="section-subtitle">Industry-recognized credentials that employers are looking for</p>
            </div>
            <div class="certifications-grid" id="certificationsGrid">
                <!-- Certification cards will be generated by JavaScript -->
            </div>
            <div class="section-cta">
                <a href="#certifications-page" class="btn btn-secondary" onclick="showAllCertifications(event)">View All Certifications</a>
            </div>
        </div>
    </section>