<section class="success-stories-section" id="success-stories">
        <div class="container">
            <div class="section-header">
                <h2 class="section-title">Success Stories</h2>
                <p class="section-subtitle">Real career transformations powered by certification</p>
            </div>
            <div class="success-stories-grid" id="successStoriesGrid">
                <!-- Success stories will be generated by JavaScript -->
            </div>
        </div>
    </section>