<section class="testimonials" id="testimonials">
        <div class="container">
            <div class="section-header">
                <h2 class="section-title">What Our Students Say</h2>
                <p class="section-subtitle">Real success stories from certified professionals</p>
            </div>
            <div class="testimonials-carousel">
                <button class="carousel-btn prev" onclick="moveCarousel(-1)">‹</button>
                <div class="testimonials-wrapper" id="testimonialsWrapper">
                    <!-- Testimonials will be generated by JavaScript -->
                </div>
                <button class="carousel-btn next" onclick="moveCarousel(1)">›</button>
            </div>
            <div class="carousel-dots" id="carouselDots"></div>
        </div>
    </section>